### ISSUE TITLE
Laravel 5. exception 'BadMethodCallException' with message 'Call to undefined method [package]'

### ISSUE THREAD

**Issue by BrunoQuaresma** [Zizaco/entrust#232]
After installed i tried run the artisan command....

```
$ php artisan
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:111
Stack trace:
#0 C:\Users\Dev\Code\ead\vendor\zizaco\entrust\src\Entrust\EntrustServiceProvider.php(21): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 C:\Users\Dev\Code\ead\vendor\zizaco\entrust\src\Entrust\EntrustServiceProvider.php(21): Zizaco\Entrust\EntrustServiceProvider->package('zizaco/entrust', 'entrust', 'C:\\Users\\Dev\\Co...')
#2 [internal function]: Zizaco\Entrust\EntrustServiceProvider->boot()
#3 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Container\Container.php(530): call_user_func_array(Array, Array)
#4 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(564): Illuminate\Container\Container->call(Array)
#5 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(546): Illuminate\Foundation\Application->bootProvider(Object(Zizaco\Entrust\EntrustServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Zizaco\Entrust\EntrustServiceProvider), 17)
#7 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(547): array_walk(Array, Object(Closure))
#8 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(141): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 C:\Users\Dev\Code\ead\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 C:\Users\Dev\Code\ead\artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
```

**Comment by andrewelkins** [comment]
Please test with the [laravel-5](https://github.com/Zizaco/entrust/tree/laravel-5) branch
